# Generated by Django 5.0.1 on 2024-02-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creat_at', models.DateField(auto_now_add=True)),
                ('codigo_cliente', models.CharField(default='Não informado', null=True)),
                ('loja_cliente', models.CharField(default='Não informado', null=True)),
                ('nome_do_cliente', models.CharField(default='Não informado', null=True)),
                ('cnpj_do_cliente', models.CharField(default='Não informado', null=True)),
                ('cnpj_de_faturamento', models.CharField(default='Não informado', null=True)),
                ('cnpj_de_remessa', models.CharField(default='Não informado', null=True)),
                ('equipamento', models.CharField(default='Não informado', null=True)),
                ('nota_de_remessa', models.CharField(default='Não informado', null=True)),
                ('data_de_remessa', models.DateField(default=None, null=True)),
                ('serie_da_nf_remessa', models.CharField(default='Não informado', null=True)),
                ('produto', models.CharField(default='Não informado', null=True)),
                ('descricao_do_produto', models.CharField(default='Não informado', null=True)),
                ('quantidade', models.CharField(default='Não informado', null=True)),
                ('projeto', models.CharField(default='Não informado', null=True)),
                ('obra', models.CharField(default='Não informado', null=True)),
                ('prazo_do_contrato', models.CharField(default='Não informado', null=True)),
                ('data_de_ativacao_legado', models.DateField(default=None, null=True)),
                ('data_de_ativacao', models.DateField(default=None, null=True)),
                ('ultimo_faturamento', models.DateField(default=None, null=True)),
                ('data_do_termo', models.DateField(default=None, null=True)),
                ('aniversario', models.DateField(default=None, null=True)),
                ('desc_ajuste', models.CharField(default='Não informado', null=True)),
                ('indice_aplicado', models.CharField(default='Não informado', null=True)),
                ('dias_de_locacao', models.CharField(default='Não informado', null=True)),
                ('valor_de_origem', models.CharField(default='Não informado', null=True)),
                ('valor_unitario', models.CharField(default='Não informado', null=True)),
                ('valor_bruto', models.CharField(default='Não informado', null=True)),
                ('tipo_do_mes', models.CharField(default='Não informado', null=True)),
                ('contrato_legado', models.CharField(default='Não informado', null=True)),
                ('acrescimo', models.CharField(default='Não informado', null=True)),
                ('franquia', models.CharField(default='Não informado', null=True)),
                ('id_equipamento', models.CharField(default='Não informado', null=True)),
                ('id_equip_substituido', models.CharField(default='Não informado', null=True)),
                ('data_da_substituicao', models.DateField(default=None, null=True)),
                ('data_proximo_faturamento', models.DateField(default=None, null=True)),
                ('data_fim_locacao', models.DateField(default=None, null=True)),
                ('tipo_de_servico', models.CharField(default='Não informado', null=True)),
                ('email', models.CharField(default='Não informado', null=True)),
                ('calculo_reajuste', models.CharField(default='Não informado', null=True)),
                ('nome_da_obra', models.CharField(default='Não informado', null=True)),
                ('numero_da_as', models.CharField(default='Não informado', null=True)),
                ('pedido_faturamento', models.CharField(default='Não informado', null=True)),
                ('nf_de_faturamento', models.CharField(default='Não informado', null=True)),
                ('serie_de_faturamento', models.CharField(default='Não informado', null=True)),
                ('data_de_faturamento', models.DateField(default=None, null=True)),
                ('qtde_faturamento', models.CharField(default='Não informado', null=True)),
                ('vlr_unitario_faturamento', models.CharField(default='Não informado', null=True)),
                ('vlr_total_faturamento', models.CharField(default='Não informado', null=True)),
                ('periodo_de_faturamento', models.CharField(default='Não informado', null=True)),
                ('status_de_cobranca', models.CharField(default='Não informado', null=True)),
            ],
            options={
                'db_table': 'testepedidosfaturados',
                'managed': False,
            },
        ),
    ]
