# Generated by Django 5.0.1 on 2024-01-30 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creatAt', models.DateTimeField(auto_now_add=True)),
                ('updatAt', models.DateTimeField(auto_now=True)),
                ('codigo_cliente', models.CharField(default='Não informado', max_length=100, null=True)),
                ('loja_cliente', models.CharField(default='Não informado', max_length=100, null=True)),
                ('nome_do_cliente', models.CharField(default='Não informado', max_length=100, null=True)),
                ('cnpj_do_cliente', models.CharField(default='Não informado', max_length=100, null=True)),
                ('cnpj_de_faturamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('cnpj_de_remessa', models.CharField(default='Não informado', max_length=100, null=True)),
                ('equipamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('nota_de_remessa', models.CharField(default='Não informado', max_length=100, null=True)),
                ('data_de_remessa', models.CharField(default='Não informado', max_length=100, null=True)),
                ('serie_da_nf_remessa', models.CharField(default='Não informado', max_length=100, null=True)),
                ('produto', models.CharField(default='Não informado', max_length=100, null=True)),
                ('descricao_do_produto', models.CharField(default='Não informado', max_length=100, null=True)),
                ('quantidade', models.IntegerField(default='Não informado', null=True)),
                ('pedido_remessa', models.CharField(default='Não informado', max_length=100, null=True)),
                ('projeto', models.CharField(default='Não informado', max_length=100, null=True)),
                ('obra', models.CharField(default='Não informado', max_length=100, null=True)),
                ('prazo_do_contrato', models.CharField(default='Não informado', max_length=100, null=True)),
                ('data_de_ativacao_legado', models.CharField(default='Não informado', max_length=100, null=True)),
                ('data_de_ativacao', models.CharField(default='Não informado', max_length=100, null=True)),
                ('ultimo_faturamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('data_do_termo', models.CharField(default='Não informado', max_length=100, null=True)),
                ('aniversario', models.CharField(default='Não informado', max_length=100, null=True)),
                ('desc_ajuste', models.CharField(default='Não informado', max_length=100, null=True)),
                ('indice_aplicado', models.CharField(default='Não informado', max_length=100, null=True)),
                ('dias_de_locacao', models.CharField(default='Não informado', max_length=100, null=True)),
                ('valor_de_origem', models.CharField(default='Não informado', max_length=100, null=True)),
                ('valor_unitario', models.CharField(default='Não informado', max_length=100, null=True)),
                ('valor_bruto', models.CharField(default='Não informado', max_length=100, null=True)),
                ('tipo_do_mes', models.CharField(default='Não informado', max_length=100, null=True)),
                ('contrato_legado', models.CharField(default='Não informado', max_length=100, null=True)),
                ('acrescimo', models.CharField(default='Não informado', max_length=100, null=True)),
                ('franquia', models.CharField(default='Não informado', max_length=100, null=True)),
                ('id_equipamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('id_equip_substituido', models.CharField(default='Não informado', max_length=100, null=True)),
                ('data_da_substituicao', models.CharField(default='Não informado', max_length=100, null=True)),
                ('data_proximo_faturamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('data_fim_locacao', models.CharField(default='Não informado', max_length=100, null=True)),
                ('tipo_de_servico', models.CharField(default='Não informado', max_length=100, null=True)),
                ('email', models.CharField(default='Não informado', max_length=100, null=True)),
                ('calculo_reajuste', models.CharField(default='Não informado', max_length=100, null=True)),
                ('nome_da_obra', models.CharField(default='Não informado', max_length=100, null=True)),
                ('numero_da_as', models.CharField(default='Não informado', max_length=100, null=True)),
                ('pedido_faturamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('nf_de_faturamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('serie_de_faturamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('data_de_faturamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('qtde_faturamento', models.IntegerField(default='Não informado', null=True)),
                ('vlr_unitario_faturamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('vlr_total_faturamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('periodo_de_faturamento', models.CharField(default='Não informado', max_length=100, null=True)),
                ('status_de_cobranca', models.CharField(default='Não informado', max_length=100, null=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='criado pelo usuário:')),
            ],
        ),
    ]
