# Generated by Django 4.2.9 on 2024-02-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='database',
            table='pedidosfaturados',
        ),
    ]
